# Generated by Django 5.1.2 on 2024-10-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbalance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
